### ISSUE TITLE
Persistent problem with several Scratch projects

### ISSUE THREAD

**Issue by NogitsuneX** [jemole/drScratch#1]
Hello! I work as a research assistant for a research involving Scratch projects and have to evaluate them using Dr. Scratch website. Unfortunately, I've encountered problems using it more than once. For approximately 70% of the projects the site consistently returns "There was an error analyzing your project" screen, and several days later it suddenly can analyze some of them (still not all). For a smaller amount of projects, the site returns "Server error 500" screen as a result and refuses to analyze the project even after several days. The research involves a lot of projects and I would really appreciate your help in resolving those existing issues as soon as possible. Thank you in advance.

**Comment by jemole** [comment]
Hi!
Fisrt of all, it's great to hear that you guys are using Dr. Scratch, and we'd love to know more about the way you are using the tool. Why don't you drop us a line at team [at] drscratch.org?
Regarding the issues you mentioned, we have problems with getsb2 when analyzing lots of projects in a small amount of time. We are working on it, but we don't have a perfect solution yet (we are a small team!).
On the other hand, when projects include non-ascii characters in the defined blocks or when they include blocks from extensions (like the Lego Wedo, for instance) the tool sometimes returns a 500 error. Hopefully, these issues will be fixed soon.
Thank you for your message!

**Comment by jemole** [comment]
I forgot to mention that, when having issues analyzing a project by its url, you can try to analyze it using the .sb2 file. This way you avoid the getsb2 issues.

**Comment by NogitsuneX** [comment]
​Hello! Thank you for the prompt answer!
I forgot to mention that I'm analyzing .sb2 files, not urls, and still get
the "We're sorry..." message. So can I do something about analyzing the
files, or is it the same problem? Or what intervals of time are best for
getting optimal results?

Thank you in advance.

On Fri, Jul 10, 2015 at 6:50 PM, Jesús Moreno León <notifications@github.com

**Comment by jemole** [comment]
If you could you please attach some of those .sb2 files, we'll take a look at them and try to figure out what exactly is going on with them.

**Comment by NogitsuneX** [comment]
Sure.

I've attached several of those projects, they all return the "we're
sorry.." screen when analyzed.
FYI, my mistake, those are .sb files.

Thank you!



On Fri, Jul 10, 2015 at 7:40 PM, Jesús Moreno León <notifications@github.com

**Comment by jemole** [comment]
I can't download the .sb files. Could you please send them to team[at]drscratch.org?

**Comment by pfherring** [comment]
Marked some 15 via the url and a couple sb2 files successfully. Then had 2 files fail and now this url: https://scratch.mit.edu/projects/72482268/

Would love to know what the student (whose project it is) can do to reduce this error occuring.

Ta, Paul

**Comment by jemole** [comment]
Hi Paul,

I have just analyzed the project 72482268 and it worked fine. Sometimes, when there are multiple parallel connections, we have problems at downloading projects from its url, so it could be one of those issues.

If you send us the sb2 files of the other two projects that you mentioned at team[at]drscratch.org we could study them and try to find out the problem.

Thanks!
