### ISSUE TITLE
Dr. Scratch for sb3 file 

### ISSUE THREAD

**Issue by WanliUF** [jemole/drScratch#13]
Dear colleague, 

We are working on a research of scratch projects. Dr. Scratch is a great tool to help us analyze projects. We have millions of projects to evaluate and it is hard to evaluate them one by one on the website. We found the GitHub of Dr. Scratch did not include the recent change for sb3 file analysis. Could you kindly share with us the latest change so that we could do the evaluation offline? We appreciate your help!

Thank you very much. 

Best, 
Wanli

**Comment by gregoriorobles** [comment]
Hi, Wanli

you can find that functionality in Angela's repo, which is, if I am not wrong: https://github.com/AngelaVargas/drscratchv3

regards, Gregorio

**Comment by WanliUF** [comment]
Hi Gregorio,

  Thank you so much for your help. I will look into Angela’s repo.

Thanks again!

Best,
Wanli
------------------------------------------------------------
Wanli Xing, Ph.D.
Assistant Professor, Educational Technology
School of Teaching & Learning
College of Education | University of Florida
PO Box 117048 | 2-215 Norman Hall | Gainesville, FL 32611
Office: (352) 273-3259

[UFsignature]
The Gator Nation
