### ISSUE TITLE
Cannot evaluate any projects

### ISSUE THREAD

**Issue by rosensh** [jemole/drScratch#16]
Thank you for developing such a helpful tool. While I was trying to evaluate some open-source scratch projects for research 
purposes on the website (http://www.drscratch.org/), I realized the evaluator was not reading any of the projects. Every time when I put a project URL, it returned a message saying "Error! Your project doesn't exist in Scratch's servers". Even some of the projects I had no issue evaluating back in December 2021 now return the same message and I cannot evaluate any projects at the moment. I also tried downloading the project locally and uploading it from my computer instead of putting the project URL but it says "CSRF verification failed. Request aborted." I have attached the image of the error below. I assume there is a need to add `django.middleware.csrf.CsrfResponseMiddleware ` Could you please fix it? I am looking forward to hearing from you
![Screen Shot 2022-06-16 at 7 44 45 AM](https://user-images.githubusercontent.com/74863286/173961033-dd859b4e-a388-45d0-aefc-3fac3992fe14.png)

**Comment by wierbicki** [comment]
When I try to analyze a project, I get "Server Error (500)".

**Comment by gregoriorobles** [comment]
Hi, @wierbicki, could you please specify what project you are trying to analyze?

thanks, Gregorio

**Comment by wierbicki** [comment]
Hello @gregoriorobles, thank you for asking. In the meantime DrScratch is working again. It seems that there was a temporary problem.

**Comment by gregoriorobles** [comment]
Thanks for the reply, @wierbicki. I am closing this issue then.
