### ISSUE TITLE
KeyError at /selector

### ISSUE THREAD

**Issue by niccokunzmann** [jemole/drScratch#3]
Hello, 

I encountered an Error, File attached. If you want to analyze the File again, it can be found [here](https://github.com/CoderDojoPotsdam/projects/blob/master/Scratch%20Projects/Platform-Bob.sb).

Hm, Github should change.

**Comment by jemole** [comment]
Hi Nicco,

We'll look into it more carefully, but it looks that there's something wrong with the way the 'Level' variable is stored in the .sb file. We have uploaded your file to the Scratch website and then downloaded it as .sb2 file, after which we could analyze it without problems with Dr. Scratch.

Really nice project, by the way!
