### ISSUE TITLE
Could you make this tool compatible with Snap?

### ISSUE THREAD

**Issue by q2dg** [jemole/drScratch#4]
Thanks!

**Comment by jemole** [comment]
At this moment we don't have enough resources to work on that feature. It is not a technical problem, but an economical one.

Nonetheless we are working in offering a pluginable architecture that will separate the front and back ends. This way it will be much easier to create plugins for analyzing programs coded in a specific language, like SNAP, and connect them to the website.

**Comment by q2dg** [comment]
Ok, thanks a lot!
I'll close this issue, then, if you don't mind.
