### ISSUE TITLE
[ V-Offline(Progracademy) ] -  Doubts about the Development Environment

### ISSUE THREAD

**Issue by bvpenaloza** [jemole/drScratch#7]
Hello,
Someone will know what development environment has been favorable to generate the anailsis of scratch projects with drScratch.

Let me explain: I need to run DrScratch locally and I have tried several development environments but I have not been successful in generating a successful analysis of a Scratch project.

> **Development environment** 
>      OS windows 10
>      python 2.7.14
>      django 1.7
>      hairball 0.3
>      kurt 2.0.5

if it is necessary to change the operating system 
or version of any tool 
or even if there is a missing tool to be able to run the DrScratch project,
it would be very helpful

**Comment by gregoriorobles** [comment]
I've used it successfully with Ubuntu.

**Comment by bvpenaloza** [comment]
ok I will try
but what version of ubuntu did you use.?

**Comment by gregoriorobles** [comment]
I don't think the Ubuntu version makes a difference if you choose any of the latest. But I'd recommend to use the latest LTS: 16.04.

**Comment by bvpenaloza** [comment]
Gregorio I have not yet been able to solve the problem with Ubuntu

**Test One (1) - OS Ubuntu 16.04 LTS**
> python 2.7.14
> django 1.7
> kurt 2.0.7 
>
> hairball 0.1rc2 
> **Answer with hairball 0.1rc2 **
> TypeError: 'NoneType' object is not iterable
>
> hairball 0.3
> **Answer with hairball 0.3 **
> Cannot find plugin mastery.Mastery
> No plugins loaded. Goodbye!


**Test One (2) - OS Ubuntu 14.04 LTS**
> python 2.7.14
> django 1.7
> kurt 2.0.7 
>
> hairball 0.1rc2 
> **Answer with hairball 0.1rc2 **
> TypeError: 'NoneType' object is not iterable
>
> hairball 0.3
> **Answer with hairball 0.3 **
> Cannot find plugin mastery.Mastery
> No plugins loaded. Goodbye!


**Test One (3) - OS Ubuntu 12.04 LTS**
> the same answer

**Comment by gregoriorobles** [comment]
@jemole can you look at this, please?

**Comment by jemole** [comment]
The error " Cannot find plugin mastery.Mastery. No plugins loaded." seems to indicate that Mastery plugin is not in the default plugins directory.

Once you installed the original hairball distribution you should replace its files with the ones in our fork.

**Comment by bvpenaloza** [comment]
**wow ... 
ready, it works ... !!! 
I am very grateful @gregoriorobles  and @jemole**

**Comment by jemole** [comment]
Congratulation!!!
